---
title: "Untitled"
output: html_document
date: "2023-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

transit center shapefile
```{r}
shape = read_sf(dsn = '/Users/chanks/workspace/capstone/data/shapefiles/tm_tran_cen', 
                layer = 'tm_tran_cen')

shape_coords = st_transform(shape,"+proj=longlat +ellps=WGS84 +datum=WGS84") %>% st_coordinates()

shape = bind_cols(shape, shape_coords) %>% rename(lat = Y, lon = X)
```

Creating a route max of max blue line 
```{r}
shape2 = read_sf(dsn = '/Users/chanks/workspace/capstone/data/shapefiles/tm_route_stops', 
                layer = 'tm_route_stops')

shape2_coords = st_transform(shape2,"+proj=longlat +ellps=WGS84 +datum=WGS84") %>% st_coordinates()

shape2 = bind_cols(shape2, shape2_coords) %>% rename(lat = Y, lon = X)


```

```{r}
max_blue = shape2 %>% filter(rte == 100)
```

```{r}
ggplot() + geom_sf(data = tri_county_tracts) + 
          #geom_sf(data = max_blue, color = "blue", size = 1) + 
          geom_line(data = max_blue, aes(x = lon, y = lat), color = 'blue', size = 1 ) + 
          labs(title =  "TriMet MAX Blue Line") +
          #geom_sf_text(data = shape, aes(label = name), size = 2, nudge_y = -.0002) + 
          coord_sf(xlim=c(-123.1, -122.4), ylim = c(45.3,45.6)) 
```

Max Red Line 
```{r}
max_red =  shape2 %>% filter(rte == 90 & dir == 0) %>% arrange(stop_seq)

ggplot() + geom_sf(data = tri_county_tracts) + 
          geom_sf(data = max_red, color = "red", size = 1) + 
          geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1) + 
          labs(title =  "TriMet MAX Red Line") +
          coord_sf(xlim=c(-122.9, -122.5), ylim = c(45.45,45.6)) 

?geom_path()
view(max_red)
```

Red and Blue 
```{r}
ggplot() + geom_sf(data = tri_county_tracts) + 
          #geom_sf(data = max_blue, color = "blue", size = 1) + 
          geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1, alpha = .5) + 
           geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = .5) +
          labs(title =  "TriMet MAX Blue Line") +
          coord_sf(xlim=c(-123.1, -122.4), ylim = c(45.3,45.6)) 
```
Now the rest of the max lines: yellow, orange, green 
```{r}
max_green = shape2 %>% filter(rte == 200 & dir == 0) %>% arrange(stop_seq)
max_orange =  shape2 %>% filter(rte == 290 & dir == 0) %>% arrange(stop_seq)
max_yellow = shape2 %>% filter(rte == 190 & dir == 0) %>% arrange(stop_seq)


ggplot() + geom_sf(data = tri_county_tracts) + 
          geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1, alpha = .5) + 
          geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = .5) +
          geom_path(data = max_yellow, aes(x = lon, y = lat), color = "yellow", size = 1, alpha = .5) +
          geom_path(data = max_orange, aes(x = lon, y = lat), color = "orange", size = 1, alpha = .5) +
          geom_path(data = max_green, aes(x = lon, y = lat), color = "green", size = 1, alpha = .5) +
          labs(title =  "TriMet MAX Lines") +
          coord_sf(xlim=c(-123.01, -122.38), ylim = c(45.40,45.6)) 
```

now to plot these routes with the transit centers: 

```{r}
ggplot() + geom_sf(data = tri_county_tracts) + 
          geom_point(data = shape %>% filter(!city %in% c("Lake Oswego","Tigard", "Oregon City") & !str_detect(name, "Barbur")), aes(x = lon, y = lat), color = "black", size = 3, shape = 17 ) + 
          geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1, alpha = .5) + 
          geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = .5) +
          geom_path(data = max_yellow, aes(x = lon, y = lat), color = "yellow", size = 1, alpha = .5) +
          geom_path(data = max_orange, aes(x = lon, y = lat), color = "orange", size = 1, alpha = .5) +
          geom_path(data = max_green, aes(x = lon, y = lat), color = "green", size = 1, alpha = .5) +
          labs(title =  "TriMet MAX System") +
          coord_sf(xlim=c(-123.1, -122.4), ylim = c(45.40,45.6)) 
```
Now we have to add our security data layer to make this actually insightful: 

```{r}
ggplot() +
  geom_sf(data = tri_county_tracts) +
  geom_point(data = top15_tracts_2022 %>% group_by(location_id) %>% summarize(n = n(), lon, lat) %>% distinct(n, lon, lat), 
             aes(x = lon, y = lat, size = n), color = 'blue', alpha = .5) +
  geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1, alpha = .5) + 
  geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = .5) +
  geom_path(data = max_yellow, aes(x = lon, y = lat), color = "yellow", size = 1, alpha = .5) +
  geom_path(data = max_orange, aes(x = lon, y = lat), color = "orange", size = 1, alpha = .5) +
  geom_path(data = max_green, aes(x = lon, y = lat), color = "green", size = 1, alpha = .5) +
  labs(title =  "TriMet MAX System") +
  coord_sf(xlim=c(-123.1, -122.4), ylim = c(45.40,45.6)) +
  theme(legend.position = "none") 
```

Adding chloropleth layer to map 
```{r}
incident_per_tract_2022= df3 %>% filter(year == 2022) %>% group_by(tractce) %>%
  count() %>% left_join(df3 %>% select(tractce,namelsadco, geometry.y), by = "tractce") %>% distinct()

ggplot() +
  geom_sf(data = incident_per_tract_2022, aes(geometry = geometry.y, fill = log(n)), alpha = .7) + # logging n to condense the scale to show more variation 
  geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1, alpha = .5) + 
  geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = .5) +
  geom_path(data = max_yellow, aes(x = lon, y = lat), color = "yellow", size = 1, alpha = .5) +
  geom_path(data = max_orange, aes(x = lon, y = lat), color = "orange", size = 1, alpha = .5) +
  geom_path(data = max_green, aes(x = lon, y = lat), color = "green", size = 1, alpha = .5) + 
  scale_fill_gradient(
      low = "white",
      high = "darkred",
      na.value = "grey50") +
   coord_sf(xlim=c(-123.1, -122.4), ylim = c(45.40,45.6)) + 
  labs(title = "Trimet Security Incident Hotspots, 2022") 
```

```{r}
library(viridis)

ggplot() +
  geom_sf(data = incident_per_tract_2022, aes(geometry = geometry.y, fill = n), alpha = .7) +
  geom_path(data = max_blue, aes(x = lon, y = lat), color = "dodgerblue", size = 1, alpha = .5) +
  coord_sf(xlim =c(-123.1, -122.4), ylim = c(45.45,45.65)) + 
  scale_fill_viridis()
```

```{r}
library(ggplot2)
library(ggmap)


api_key = "AIzaSyBd4Q6cJzX1fFUhW2qgv6eWOztnZOcTuRk"
register_google(key = api_key)

portland_map = get_map(location = 'portland, or, usa', maptype = "roadmap", source = 'google', zoom = 10)
# Define the bounding box for your plot
bbox <- c(left = -123.1, bottom = 45.45, right = -122.4, top = 45.65)

# Create the plot
p = ggmap(portland_map)


p + geom_point(data = df_may_jul_2022, aes(x = lon, y = lat)) +
  geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = 0.5) + 
  xlim(-123.1, -122.4) + 
  ylim(45.40,45.6)
```


```{r}
p + 
  geom_point(data = top15_tracts_2022 %>% group_by(location_id) %>% summarize(n = n(), lon, lat) %>% distinct(n, lon, lat), 
             aes(x = lon, y = lat, size = n), color = 'purple', alpha = .5) +
  geom_path(data = max_red, aes(x = lon, y = lat), color = "red", size = 1, alpha = .5) + 
  geom_path(data = max_blue, aes(x = lon, y = lat), color = "blue", size = 1, alpha = .5) +
  geom_path(data = max_yellow, aes(x = lon, y = lat), color = "yellow", size = 1, alpha = .5) +
  geom_path(data = max_orange, aes(x = lon, y = lat), color = "orange", size = 1, alpha = .5) +
  geom_path(data = max_green, aes(x = lon, y = lat), color = "green", size = 1, alpha = .5) +
  labs(title =  "TriMet MAX System") +
  xlim(-123.1, -122.4)+ 
  ylim(45.40,45.6) +
  theme(legend.position = "none") 
```
The most security incidents align with the MAX train routes. 
